### ISSUE TITLE
Crash on Warp

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/tTimers#1]
loaded addon, left mog house, cast warp, got nil ref. crash

also thank you for tackling this addon!

![image](https://github.com/ThornyFFXI/tTimers/assets/66495755/b1355ab8-8647-462c-84ea-ce8eb158043f)

**Comment by GetAwayCoxn** [comment]
Quick update, reloaded addon walked from HP1 to AH in lower J and same exact crash/line error after only a few seconds of walking

**Comment by ThornyFFXI** [comment]
should be fixed in 0.02
