### ISSUE TITLE
Possible error in timer for using a WS when too far away (or server ability ID mismatch)

### ISSUE THREAD

**Issue by ConteAlmaviva** [ThornyFFXI/tTimers#12]
![image](https://github.com/ThornyFFXI/tTimers/assets/8880996/16121352-4dd1-406a-a929-9756de26bd62)

![image](https://github.com/ThornyFFXI/tTimers/assets/8880996/137d670d-219e-459f-ba89-742382707661)

Not sure if this is maybe a private server (Horizon) specific issue, but I jumped the gun hitting a WS macro (Fast Blade) when I was out of range a bit ago, and it triggered a recast timer for Banish V.  Going to try with ~Flat Blade~ a different WS in a moment to see if I get the same or similar behavior.

**Comment by ConteAlmaviva** [comment]
Tried the same with Burning Blade a moment ago, it came up as Diaga.

**Comment by ThornyFFXI** [comment]
Recast timers are directly sourced from the games' timers in memory, so that sounds like a very much Horizon issue.  I'd be interested to see if the recast addon shows the same.

**Comment by ConteAlmaviva** [comment]
I'll try and hop on tonight to see if Recast shows the same. Thanks!

**Comment by ThornyFFXI** [comment]
Following up to see if this was ever verified to be a horizon issue or not, unable to reproduce on retail.

**Comment by ConteAlmaviva** [comment]
I am sorry this took so long to report back on, I kept spacing it when I've had time to play, but your suspicion was correct - Recast shows the same behavior.  Using Shield Break when too far away is somehow resulting in a Paralyze II recast timer:

![image](https://github.com/ThornyFFXI/tTimers/assets/8880996/efe93418-d799-44a4-b47d-67d8b3eb5e54)

Attached is the log file from a packet capture I was running while capturing this screenshot.  I'm guessing there's something in here

[full.log](https://github.com/ThornyFFXI/tTimers/files/15046418/full.log)

**Comment by ThornyFFXI** [comment]
Yea, definitely a Horizon issue then.  The action packet they are sending is setting spell recast on something entirely unrelated.
