### ISSUE TITLE
Regeneration duration is incorrect

### ISSUE THREAD

**Issue by ShiyoKozuki** [ThornyFFXI/tTimers#13]
https://github.com/ThornyFFXI/tTimers/blob/bb216859f6568d0f27077653c1da2ddc0e4fc705/durations/bluemagic.lua#L165

Should be 90s according to BG wiki
https://www.bg-wiki.com/ffxi/Regeneration

**Comment by ThornyFFXI** [comment]
Fixed in 0.12.
