### ISSUE TITLE
Mob Debuf timer

### ISSUE THREAD

**Issue by Butthatsnotall** [ThornyFFXI/tTimers#16]
I notice the debuffs are all on the same window as where I buff players, Can there be a fix for this so have mob debuffs on a different window?

**Comment by ThornyFFXI** [comment]
This is unclear.  Mob debuffs are already stored seperately, in the default layout buffs count upwards from center and debuffs count downwards from the center.  If you use the command `/tt reposition` then you can move the debuff panel independantly of the buff panel by clicking the blue part of the square handle and dragging.  If you want to change whether they count upwards or downwards, use `/tt` and edit the panel skin.

**Comment by ThornyFFXI** [comment]
Been 2 weeks and no follow up here, will need you to clarify what your issue is or I will close this.

**Comment by Butthatsnotall** [comment]
Oh yeah sry I don't check my email often I had gotten a lil help on how to move things around and its working awesomely. tryin to figure out now if I did something wrong or turned something off, I don't see smn blood pack buffs only thing that I need to figure out now lol

**Comment by ThornyFFXI** [comment]
There's no support for SMN blood pacts (yet).  Going to close this issue since the primary complaint seems to be resolved.
