### ISSUE TITLE
How to unblock timers

### ISSUE THREAD

**Issue by Kitsuneeeeeeeeee** [ThornyFFXI/tTimers#17]
Hi, I accidentally block some timers, can I know in which part of the config do I unblock them in thx.

**Comment by ThornyFFXI** [comment]
Unload addon, open the file at:
`ashita/config/addons/tTimers/Char_ID/settings.lua`


Remove the keys from Buff.Blocked, Debuff.Blocked, Recast.BlockedAbilities, Recast.BlockedSpells as needed.

There's nothing in the GUI for it yet.
