### ISSUE TITLE
Illegible font rendering on WINE/Linux

### ISSUE THREAD

**Issue by grimwaldr** [ThornyFFXI/tTimers#19]
Hello,

I think there's some issues with gdifonts and WINE/Linux - some sort of font rendering issue that makes it very hard to read. Doesn't seem to be an issue for Windows users. This is the only addon I've used that has this issue. 

See screenshot below:

![image](https://github.com/ThornyFFXI/tTimers/assets/118697420/84125b32-ba8e-4064-ae0e-8d05b00f91c9)

**Comment by ThornyFFXI** [comment]
This is outside the scope of the library, if your WINE/Linux environment is not properly implementing everything in the GDI+ and D3D pipeline used then it's an issue with your environment.

**Comment by grimwaldr** [comment]
It's possible that the older version of wine recommended for FFXI is causing issues then I'll try swapping to a more modern version of wine and see if it improves. Thanks.

**Comment by WinterSolstice8** [comment]
Seems like if you install gdifonts in winetricks it looks better

![image](https://github.com/user-attachments/assets/a874eb9f-9b96-40e5-9c3a-e93f5f3ddd7f)
![image](https://github.com/user-attachments/assets/ea7660a0-181b-4107-b21c-989ea509527a)

**Comment by ThornyFFXI** [comment]
Going to mark this resolved, since it seems clear it's an environment issue and others have found the same resolution in the Ashita discord.
