### ISSUE TITLE
Fonts not included by default

### ISSUE THREAD

**Issue by Flowingwillow** [ThornyFFXI/tTimers#22]
Program doesn't work as is, require to install fonts to make it work (fonts obtained from https://github.com/ThornyFFXI/gdifonts)

Also sorry if this isn't how to submit feedback/bugs, wanted to help, thanks for the addons ♥

**Comment by ThornyFFXI** [comment]
It is included, you should be using the release link on the right not 'download as zip'.  The gdifonts lib is a submodule, so using a proper git clone will get it, the zip will not.  This is normal, end users should always look for a release when downloading from github.

**Comment by Flowingwillow** [comment]
Thanks!
