### ISSUE TITLE
Blue handles not shown when using /tt reposition

### ISSUE THREAD

**Issue by biancs** [ThornyFFXI/tTimers#8]
I'm unable to move the bars around when using the command as there are no blue bars to use

<img width="358" alt="image" src="https://github.com/ThornyFFXI/tTimers/assets/28443239/e445ff49-2d47-43fb-81b0-ef5cdf248818">

I was trying to find bars when I somehow moved the debuffs but not sure how that happened.

All I can think of is it being some sort of resolution issue?

**Comment by ThornyFFXI** [comment]
your screenshot shows them, they are rounded squares at the top left of the normal layout and bottom left of the bottom justified layout

**Comment by biancs** [comment]
Thank you for the clarification, I didn't realize that's what they looked like. Appreciate it!
