### ISSUE TITLE
Suggestion for repositioning

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/tTimers#9]
Seems a few people think they don't have the blue box handles to reposition when they are just not seeing them. It seems like they are being mistaken for the icon. I am not sure how much of a hassle this will be in the long run, I am thinking this same question will get asked to you over and over. If possible to not display any icons on any timers while in reposition mode? I think that might make the blue box stand out more for people and hopefully reduce the amount of times you are about to get this question over the next several months. Maybe you have a better idea or maybe this isn't really an issue your concerned about, just wanted to offer a suggestion.

**Comment by ThornyFFXI** [comment]
I want the icons to remain to provide a preview when repositioning, but I hadn't considered how closely the handles size and position was to that of the icons.  I think doubling the size of the handle might be better than removing them.

**Comment by ThornyFFXI** [comment]
reworked drag handles a bit in 0.08, hopefully good now
